// --- TAMBAHAN 150 ITEM BARU ---
Object.assign(ITEM_DB, {
    // --- WEAPONS (wpn_008 - wpn_050) ---
    "wpn_008": { name: "Gada Kayu Berpaku", type: "weapon", val: 30, desc: "Kasar tapi efektif menghancurkan tulang.", atk: 12 },
    "wpn_009": { name: "Rapier Perak", type: "weapon", val: 150, desc: "Sangat ringan, favorit bangsawan Aerthale.", atk: 18, agi: 5 },
    "wpn_010": { name: "Claymore Karat", type: "weapon", val: 90, desc: "Pedang dua tangan yang sangat berat.", atk: 35, spd: -4 },
    "wpn_011": { name: "Staf Magang", type: "weapon", val: 50, desc: "Kayu yang dialiri sedikit mana.", atk: 5, mag: 10 },
    "wpn_012": { name: "Busur Recurve Baja", type: "weapon", val: 200, desc: "Tarikan berat, daya tembus tinggi.", atk: 28, range: true },
    "wpn_013": { name: "Kapak Perang Ganda", type: "weapon", val: 180, desc: "Senjata para penjaga gerbang Valeryn.", atk: 40, spd: -3 },
    "wpn_014": { name: "Scythe Petani", type: "weapon", val: 20, desc: "Alat tani yang dipaksa jadi senjata.", atk: 9 },
    "wpn_015": { name: "Katana Impor", type: "weapon", val: 450, desc: "Bilah eksotis dari seberang laut Marrowport.", atk: 32, crit: 10 },
    "wpn_016": { name: "Warhammer Batu", type: "weapon", val: 140, desc: "Dibuat dari granit Stonehollow.", atk: 45, spd: -5 },
    "wpn_017": { name: "Crossbow Ringan", type: "weapon", val: 110, desc: "Mekanisme pegas yang andal.", atk: 22, range: true },
    "wpn_018": { name: "Trident Nelayan", type: "weapon", val: 55, desc: "Biasa digunakan melawan monster air.", atk: 16 },
    "wpn_019": { name: "Flail Berduri", type: "weapon", val: 130, desc: "Sulit dikendalikan, sulit ditangkis.", atk: 24 },
    "wpn_020": { name: "Staf Kristal Biru", type: "weapon", val: 600, desc: "Fokus sihir murni dari Aerthale.", atk: 12, mag: 40 },
    "wpn_021": { name: "Bilah Bayangan", type: "weapon", val: 800, desc: "Hampir tidak terlihat di kegelapan.", atk: 30, stealth: 15 },
    "wpn_022": { name: "Palu Hakim", type: "weapon", val: 300, desc: "Memberikan efek stun pada musuh.", atk: 38, effect: "stun" },
    "wpn_023": { name: "Busur Longbow Oak", type: "weapon", val: 170, desc: "Jarak tembak yang luar biasa.", atk: 25, range: true },
    "wpn_024": { name: "Katar Berkarat", type: "weapon", val: 40, desc: "Senjata genggam untuk serangan cepat.", atk: 10, spd: 3 },
    "wpn_025": { name: "Halberd Penjaga", type: "weapon", val: 250, desc: "Kombinasi tombak dan kapak.", atk: 36 },
    "wpn_026": { name: "Sabre Perwira", type: "weapon", val: 220, desc: "Bilah melengkung untuk kavaleri.", atk: 27 },
    "wpn_027": { name: "Cestus Perunggu", type: "weapon", val: 60, desc: "Sarung tangan tempur untuk petarung jarak dekat.", atk: 14 },
    "wpn_028": { name: "Wand Kayu Willow", type: "weapon", val: 80, desc: "Cocok untuk mantra penyembuh.", atk: 3, mag: 15 },
    "wpn_029": { name: "Greatsword Api", type: "weapon", val: 1200, desc: "Ditempa dengan darah naga api.", atk: 65, element: "fire" },
    "wpn_030": { name: "Shortsword Berlapis Emas", type: "weapon", val: 500, desc: "Lebih untuk status daripada perang.", atk: 20, charisma: 5 },
    "wpn_031": { name: "Tombak Es", type: "weapon", val: 950, desc: "Dingin saat disentuh.", atk: 42, element: "ice" },
    "wpn_032": { name: "Morning Star", type: "weapon", val: 160, desc: "Bola besi berduri dengan rantai.", atk: 29 },
    "wpn_033": { name: "Pisau Lempar (Set)", type: "weapon", val: 45, desc: "Satu set isi 5 pisau kecil.", atk: 15, range: true },
    "wpn_034": { name: "Gada Suci", type: "weapon", val: 400, desc: "Diberkati oleh pendeta Thornwall.", atk: 22, holy: 20 },
    "wpn_035": { name: "Kapak Lempar", type: "weapon", val: 70, desc: "Keseimbangan yang sempurna.", atk: 20, range: true },
    "wpn_036": { name: "Bilah Angin", type: "weapon", val: 850, desc: "Sangat ringan, memotong udara.", atk: 34, spd: 8 },
    "wpn_037": { name: "Palu Penghancur Perisai", type: "weapon", val: 320, desc: "Bonus damage terhadap armor.", atk: 30, armor_pen: 20 },
    "wpn_038": { name: "Busur Pendek Darkwood", type: "weapon", val: 280, desc: "Kayu hitam yang sangat kuat.", atk: 33 },
    "wpn_039": { name: "Tombak Kavaleri", type: "weapon", val: 210, desc: "Mematikan saat digunakan berkuda.", atk: 45 },
    "wpn_040": { name: "Dagger Ritual", type: "weapon", val: 190, desc: "Digunakan dalam upacara terlarang.", atk: 15, mag: 10 },
    "wpn_041": { name: "Great-axe Berserker", type: "weapon", val: 750, desc: "Meningkatkan amarah pemakainya.", atk: 55, spd: -6 },
    "wpn_042": { name: "Rapier Elektrik", type: "weapon", val: 1100, desc: "Mengalirkan percikan petir.", atk: 35, element: "lightning" },
    "wpn_043": { name: "Staf Penatua", type: "weapon", val: 1500, desc: "Pusaka dari menara Aerthale.", atk: 20, mag: 80 },
    "wpn_044": { name: "Sumpit Beracun", type: "weapon", val: 120, desc: "Senjata senyap dari rawa.", atk: 5, effect: "deadly_poison" },
    "wpn_045": { name: "Mace Bintang Jatuh", type: "weapon", val: 900, desc: "Dibuat dari meteorit.", atk: 50, crit: 15 },
    "wpn_046": { name: "Pedang Eksekutor", type: "weapon", val: 450, desc: "Ujungnya datar, berat di bilah.", atk: 48 },
    "wpn_047": { name: "Busur Badai", type: "weapon", val: 2200, desc: "Anak panah melesat secepat kilat.", atk: 60, range: true },
    "wpn_048": { name: "Tombak Naga Berduri", type: "weapon", val: 2500, desc: "Dibuat untuk menembus sisik naga.", atk: 80 },
    "wpn_049": { name: "Dagger Kristal Merah", type: "weapon", val: 350, desc: "Menyerap darah musuh.", atk: 18, lifesteal: 5 },
    "wpn_050": { name: "Palu Gempa", type: "weapon", val: 1800, desc: "Getarannya bisa meruntuhkan tembok.", atk: 70, spd: -10 },

    // --- ARMOR (arm_006 - arm_050) ---
    "arm_006": { name: "Helm Prajurit Valeryn", type: "armor", slot: "head", val: 80, desc: "Baja padat pelindung wajah.", def: 10 },
    "arm_007": { name: "Jubah Mage Magang", type: "armor", slot: "body", val: 70, desc: "Kain biru dengan serat mana.", def: 3, mag: 10 },
    "arm_008": { name: "Celana Kulit Beruang", type: "armor", slot: "legs", val: 55, desc: "Sangat tebal dan tahan dingin.", def: 6 },
    "arm_009": { name: "Sarung Tangan Besi", type: "armor", slot: "hands", val: 40, desc: "Melindungi jari dari benturan.", def: 4 },
    "arm_010": { name: "Perisai Kayu Bundar", type: "armor", slot: "offhand", val: 30, desc: "Pertahanan dasar.", def: 5 },
    "arm_011": { name: "Chainmail Ringan", type: "armor", slot: "body", val: 150, desc: "Rajutan cincin besi.", def: 12 },
    "arm_012": { name: "Plate Armor Ksatria", type: "armor", slot: "body", val: 500, desc: "Pelindung tubuh penuh dari baja.", def: 25, spd: -5 },
    "arm_013": { name: "Hood Pembunuh Bayaran", type: "armor", slot: "head", val: 120, desc: "Menutup identitas sepenuhnya.", def: 4, crit: 5 },
    "arm_014": { name: "Greaves Perunggu", type: "armor", slot: "legs", val: 90, desc: "Pelindung kaki yang mengkilap.", def: 8 },
    "arm_015": { name: "Shield of the Lion", type: "armor", slot: "offhand", val: 400, desc: "Perisai besar dengan lambang singa.", def: 18 },
    "arm_016": { name: "Jubah Pengelana Hutan", type: "armor", slot: "body", val: 85, desc: "Warna hijau menyatu dengan alam.", def: 6, stealth: 10 },
    "arm_017": { name: "Helm Tanduk Kerbau", type: "armor", slot: "head", val: 110, desc: "Terlihat sangat mengintimidasi.", def: 9, str: 2 },
    "arm_018": { name: "Sepatu Bot Sutra", type: "armor", slot: "legs", val: 130, desc: "Langkah kaki menjadi tanpa suara.", def: 2, spd: 5 },
    "arm_019": { name: "Bracer Kulit Reptil", type: "armor", slot: "hands", val: 75, desc: "Tahan terhadap goresan.", def: 5 },
    "arm_020": { name: "Cape Aerthale", type: "armor", slot: "back", val: 200, desc: "Meningkatkan regenerasi mana.", def: 2, m_reg: 5 },
    "arm_021": { name: "Scale Mail Naga", type: "armor", slot: "body", val: 3000, desc: "Dibuat dari sisik naga asli.", def: 50, fire_res: 50 },
    "arm_022": { name: "Helm Kaca Obsidian", type: "armor", slot: "head", val: 650, desc: "Bisa melihat di kegelapan.", def: 15, night_vision: true },
    "arm_023": { name: "Perisai Tower", type: "armor", slot: "offhand", val: 350, desc: "Perisai setinggi tubuh.", def: 25, spd: -8 },
    "arm_024": { name: "Baju Zirah Upacara", type: "armor", slot: "body", val: 1000, desc: "Sangat indah namun berat.", def: 20, cha: 15 },
    "arm_025": { name: "Sandalias Hermes", type: "armor", slot: "legs", val: 800, desc: "Terasa seperti terbang.", def: 3, spd: 15 },
    "arm_026": { name: "Sarung Tangan Cakar", type: "armor", slot: "hands", val: 220, desc: "Memudahkan memanjat dinding.", def: 6, climb: 10 },
    "arm_027": { name: "Masker Gas Stonehollow", type: "armor", slot: "head", val: 150, desc: "Melindungi dari uap tambang.", def: 2, toxic_res: 80 },
    "arm_028": { name: "Amulet Perlindungan", type: "armor", slot: "neck", val: 300, desc: "Perisai magis pasif.", def: 5, mag_def: 10 },
    "arm_029": { name: "Belt of Giant Strength", type: "armor", slot: "waist", val: 1200, desc: "Gesper besar bertenaga raksasa.", str: 20 },
    "arm_030": { name: "Cincin Api", type: "armor", slot: "finger", val: 450, desc: "Meningkatkan serangan elemen api.", atk_fire: 15 },
    "arm_031": { name: "Mantel Bulu Yeti", type: "armor", slot: "body", val: 700, desc: "Kebal terhadap cuaca beku.", def: 15, ice_res: 70 },
    "arm_032": { name: "Helm Mithril", type: "armor", slot: "head", val: 1500, desc: "Sangat kuat dan seringan bulu.", def: 22 },
    "arm_033": { name: "Buckler Besi", type: "armor", slot: "offhand", val: 70, desc: "Perisai kecil untuk parry.", def: 6, parry: 10 },
    "arm_034": { name: "Kacamata Mekanik", type: "armor", slot: "head", val: 250, desc: "Melihat detail tersembunyi.", acc: 15 },
    "arm_035": { name: "Legging Plat Putih", type: "armor", slot: "legs", val: 400, desc: "Zirah ksatria suci.", def: 18 },
    "arm_036": { name: "Jubah Pengkhianat", type: "armor", slot: "body", val: 550, desc: "Memberi bonus serangan dari belakang.", def: 8, backstab: 20 },
    "arm_037": { name: "Crown of Kings", type: "armor", slot: "head", val: 5000, desc: "Mahkota kuno Avarath.", def: 5, all_stats: 5 },
    "arm_038": { name: "Boots of Waterwalking", type: "armor", slot: "legs", val: 900, desc: "Bisa berjalan di atas air.", def: 4 },
    "arm_039": { name: "Perisai Cermin", type: "armor", slot: "offhand", val: 1100, desc: "Memantulkan serangan sihir.", def: 15, reflect_magic: 30 },
    "arm_040": { name: "Pauldrons Berduri", type: "armor", slot: "shoulder", val: 180, desc: "Melukai musuh yang menabrak.", def: 10, thorns: 5 },
    "arm_041": { name: "Kimono Sutra Naga", type: "armor", slot: "body", val: 2000, desc: "Kain yang sangat tahan sihir.", def: 10, mag_res: 40 },
    "arm_042": { name: "Helm Penyelam", type: "armor", slot: "head", val: 300, desc: "Bernapas di bawah air Marrowport.", def: 12 },
    "arm_043": { name: "Sarung Tangan Pencuri", type: "armor", slot: "hands", val: 140, desc: "Meningkatkan persentase pickpocket.", agi: 8 },
    "arm_044": { name: "Jubah Transparan", type: "armor", slot: "body", val: 4500, desc: "Menghilang sepenuhnya saat diam.", stealth: 100 },
    "arm_045": { name: "Sandal Jerami Berkat", type: "armor", slot: "legs", val: 40, desc: "Dibuat oleh biksu Thornwall.", def: 1, luck: 5 },
    "arm_046": { name: "Plat Dada Eboni", type: "armor", slot: "body", val: 1800, desc: "Baja hitam yang menyerap cahaya.", def: 35 },
    "arm_047": { name: "Greatshield Aegis", type: "armor", slot: "offhand", val: 3500, desc: "Tak tergoyahkan.", def: 50, knockback_res: 100 },
    "arm_048": { name: "Cincin Keabadian", type: "armor", slot: "finger", val: 10000, desc: "Mencegah kematian satu kali.", auto_res: true },
    "arm_049": { name: "Bracer Emas", type: "armor", slot: "hands", val: 600, desc: "Simbol kekayaan Marrowport.", def: 8, gold_find: 20 },
    "arm_050": { name: "Helm Ksatria Tanpa Kepala", type: "armor", slot: "head", val: 2200, desc: "Mengerikan dan berhantu.", def: 20, fear_aura: 10 },

    // --- CONSUMABLES (con_006 - con_050) ---
    "con_006": { name: "Apel Segar", type: "food", val: 3, desc: "Manis dan renyah.", hunger: 15 },
    "con_007": { name: "Sup Jamur Hutan", type: "food", val: 12, desc: "Hangat, tapi hati-hati jamur beracun.", hunger: 25, mp: 5 },
    "con_008": { name: "Ramuan Mana Kecil", type: "potion", val: 30, desc: "Cairan biru bercahaya.", mp: 20 },
    "con_009": { name: "Ramuan Mana Besar", type: "potion", val: 100, desc: "Ekstrak kristal Aerthale.", mp: 80 },
    "con_010": { name: "Elixir Kekuatan", type: "potion", val: 250, desc: "Meningkatkan ATK sementara.", buff: "str", duration: 300 },
    "con_011": { name: "Bir Marrowport", type: "food", val: 8, desc: "Minuman keras pelaut.", hunger: 5, cha: 2, acc: -5 },
    "con_012": { name: "Roti Keju Thornwall", type: "food", val: 20, desc: "Sangat lezat dan bergizi.", hunger: 50 },
    "con_013": { name: "Ramuan Antidote", type: "potion", val: 45, desc: "Menetralkan segala jenis racun.", cure: "poison" },
    "con_014": { name: "Scroll of Town Portal", type: "scroll", val: 150, desc: "Teleportasi ke kota terdekat." },
    "con_015": { name: "Scroll of Fireball", type: "scroll", val: 200, desc: "Mengeluarkan bola api besar." },
    "con_016": { name: "Bom Asap", type: "item", val: 60, desc: "Gunakan untuk melarikan diri.", effect: "escape" },
    "con_017": { name: "Madu Hutan Dalam", type: "food", val: 40, desc: "Sangat manis, memulihkan stamina.", stamina: 50 },
    "con_018": { name: "Daging Naga Panggang", type: "food", val: 1000, desc: "Makanan para legenda.", hunger: 100, all_stats: 10 },
    "con_019": { name: "Ramuan Kecepatan", type: "potion", val: 180, desc: "Berlari secepat angin.", buff: "spd", duration: 120 },
    "con_020": { name: "Air Suci", type: "item", val: 120, desc: "Membakar monster undead.", dmg_undead: 100 },
    "con_021": { name: "Kue Kering Peri", type: "food", val: 300, desc: "Satu gigitan menghapus rasa lelah.", hunger: 20, mp: 100 },
    "con_022": { name: "Ramuan Kulit Besi", type: "potion", val: 220, desc: "Kulit menjadi sekeras baja.", buff: "def", duration: 180 },
    "con_023": { name: "Minyak Senjata", type: "item", val: 50, desc: "Memperbaiki durabilitas senjata.", repair: 30 },
    "con_024": { name: "Umpan Ikan Mewah", type: "item", val: 15, desc: "Menarik ikan langka." },
    "con_025": { name: "Susu Sapi Thornwall", type: "food", val: 10, desc: "Segar dan menyehatkan tulang.", hunger: 10, def_buff: 1 },
    "con_026": { name: "Ramuan Tak Terlihat", type: "potion", val: 500, desc: "Menghilang selama 60 detik.", effect: "invis" },
    "con_027": { name: "Kopi Hitam Stonehollow", type: "food", val: 25, desc: "Pahit, menghilangkan kantuk.", stamina: 30, acc: 5 },
    "con_028": { name: "Scroll of Identify", type: "scroll", val: 80, desc: "Mengetahui statistik item misterius." },
    "con_029": { name: "Obat Penenang", type: "med", val: 40, desc: "Menghilangkan efek ketakutan.", cure: "fear" },
    "con_030": { name: "Buah Beri Berkilau", type: "food", val: 150, desc: "Hanya tumbuh di bawah cahaya bulan.", mp: 50 },
    "con_031": { name: "Granat Ledak", type: "item", val: 300, desc: "Ciptaan insinyur Stonehollow.", dmg: 150, area: true },
    "con_032": { name: "Teh Herbal Aerthale", type: "food", val: 35, desc: "Menenangkan pikiran.", mp_reg: 10 },
    "con_033": { name: "Ramuan Pembesar Otot", type: "potion", val: 400, desc: "Efek str luar biasa, tapi pusing.", str: 30, int: -10 },
    "con_034": { name: "Bumbu Masak Rahasia", type: "item", val: 100, desc: "Meningkatkan kualitas makanan apa pun." },
    "con_035": { name: "Ramuan Penglihatan Malam", type: "potion", val: 120, desc: "Melihat dalam gelap tanpa obor.", duration: 600 },
    "con_036": { name: "Cuka Pembersih Karat", type: "item", val: 20, desc: "Mengembalikan kilau pedang tua." },
    "con_037": { name: "Daging Tikus Bakar", type: "food", val: 1, desc: "Putus asa? Ini solusinya.", hunger: 5, disease_risk: 10 },
    "con_038": { name: "Ramuan Nafas Api", type: "potion", val: 600, desc: "Menyemburkan api dari mulut.", dmg: 200 },
    "con_039": { name: "Scroll of Blizzard", type: "scroll", val: 450, desc: "Memanggil badai salju kecil." },
    "con_040": { name: "Garam Pengawet", type: "item", val: 5, desc: "Membuat daging tidak cepat busuk." },
    "con_041": { name: "Ramuan Awet Muda", type: "potion", val: 5000, desc: "Hanya mitos... atau bukan?", luck: 20 },
    "con_042": { name: "Arak Naga", type: "food", val: 250, desc: "Sangat panas di tenggorokan.", fire_res: 20 },
    "con_043": { name: "Bubuk Tidur", type: "item", val: 100, desc: "Membuat musuh tertidur.", effect: "sleep" },
    "con_044": { name: "Permen Energi", type: "food", val: 15, desc: "Gula murni.", stamina: 20 },
    "con_045": { name: "Ramuan Anti-Magi", type: "potion", val: 800, desc: "Kebal sihir sementara.", duration: 60 },
    "con_046": { name: "Scroll of Resurrection", type: "scroll", val: 2500, desc: "Menghidupkan rekan yang gugur." },
    "con_047": { name: "Jus Jeruk Segar", type: "food", val: 8, desc: "Kaya vitamin.", hunger: 5, hp: 2 },
    "con_048": { name: "Ramuan Pemikat Hewan", type: "potion", val: 140, desc: "Memudahkan menjinakkan monster." },
    "con_049": { name: "Scroll of Lightning Bolt", type: "scroll", val: 350, desc: "Sambaran petir tunggal." },
    "con_050": { name: "Pesta dalam Kotak", type: "food", val: 1200, desc: "Makanan lengkap untuk satu grup.", hunger: 100, team_heal: 50 },

    // --- MATERIALS (mat_006 - mat_040) ---
    "mat_006": { name: "Batu Bara", type: "material", val: 5, desc: "Bahan bakar tungku." },
    "mat_007": { name: "Benang Sutra", type: "material", val: 25, desc: "Bahan pakaian halus." },
    "mat_008": { name: "Esens Mana", type: "material", val: 150, desc: "Inti sihir yang terkonsentrasi." },
    "mat_009": { name: "Taring Harimau", type: "material", val: 40, desc: "Tajam dan kuat." },
    "mat_010": { name: "Batu Obsidian", type: "material", val: 80, desc: "Kaca vulkanik hitam." },
    "mat_011": { name: "Bulu Phoenix", type: "material", val: 1000, desc: "Selalu terasa hangat." },
    "mat_012": { name: "Minyak Ikan Paus", type: "material", val: 60, desc: "Bahan bakar lampu terbaik." },
    "mat_013": { name: "Pasir Emas", type: "material", val: 200, desc: "Hasil saringan sungai Avarath." },
    "mat_014": { name: "Tulang Raksasa", type: "material", val: 300, desc: "Sangat keras untuk bahan senjata." },
    "mat_015": { name: "Getah Pohon Tua", type: "material", val: 20, desc: "Sangat lengket, bahan lem." },
    "mat_016": { name: "Kain Linen", type: "material", val: 10, desc: "Bahan dasar pakaian." },
    "mat_017": { name: "Kristal Zamrud", type: "material", val: 500, desc: "Permata hijau yang berharga." },
    "mat_018": { name: "Kulit Naga Api", type: "material", val: 2500, desc: "Tahan panas ekstrem." },
    "mat_019": { name: "Baja Valeryn", type: "material", val: 120, desc: "Baja kualitas tertinggi." },
    "mat_020": { name: "Akar Mandrake", type: "material", val: 90, desc: "Bisa berteriak jika dicabut." },
    "mat_021": { name: "Mata Katak Beracun", type: "material", val: 15, desc: "Bahan ramuan debuff." },
    "mat_022": { name: "Cangkang Kepiting Raksasa", type: "material", val: 70, desc: "Bahan tameng organik." },
    "mat_023": { name: "Bubuk Perak", type: "material", val: 55, desc: "Efektif melawan makhluk malam." },
    "mat_024": { name: "Bulu Serigala Putih", type: "material", val: 45, desc: "Sangat lembut dan hangat." },
    "mat_025": { name: "Hati Elemental", type: "material", val: 800, desc: "Berdenyut dengan energi murni." },
    "mat_026": { name: "Tinta Gurita Raksasa", type: "material", val: 110, desc: "Bahan penulisan scroll tingkat tinggi." },
    "mat_027": { name: "Gigi Hiu", type: "material", val: 30, desc: "Gerigi alami yang tajam." },
    "mat_028": { name: "Kayu Oak", type: "material", val: 15, desc: "Kayu konstruksi standar." },
    "mat_029": { name: "Batu Meteorit", type: "material", val: 1500, desc: "Logam dari langit." },
    "mat_030": { name: "Ekor Kalajengking", type: "material", val: 65, desc: "Mengandung kantung racun." },
    "mat_031": { name: "Sayap Kelelawar", type: "material", val: 5, desc: "Bahan ramuan terbang." },
    "mat_032": { name: "Cermin Pecah", type: "material", val: 2, desc: "Hanya sampah? Atau bahan kutukan?" },
    "mat_033": { name: "Kawat Tembaga", type: "material", val: 12, desc: "Bahan teknik Stonehollow." },
    "mat_034": { name: "Mutiara Hitam", type: "material", val: 2000, desc: "Sangat langka dari dasar laut terdalam." },
    "mat_035": { name: "Lendir Slime", type: "material", val: 8, desc: "Menjijikkan tapi berguna untuk pelumas." },
    "mat_036": { name: "Kuku Gryphon", type: "material", val: 450, desc: "Keras dan melengkung tajam." },
    "mat_037": { name: "Sisik Ikan Mas", type: "material", val: 1, desc: "Tidak terlalu berguna." },
    "mat_038": { name: "Bunga Edelweiss Gletser", type: "material", val: 300, desc: "Hanya tumbuh di puncak es." },
    "mat_039": { name: "Inti Golem", type: "material", val: 900, desc: "Batu yang memberikan kehidupan." },
    "mat_040": { name: "Pasir Waktu", type: "material", val: 5000, desc: "Bahan yang sangat langka dan berbahaya." },

    // --- KEY ITEMS (key_003 - key_017) ---
    "key_003": { name: "Kunci Penjara Karat", type: "key", val: 0, desc: "Membuka sel di benteng lama." },
    "key_004": { name: "Surat Izin Dagang", type: "key", val: 100, desc: "Izin resmi masuk Marrowport." },
    "key_005": { name: "Medali Keberanian", type: "key", val: 0, desc: "Diberikan oleh Raja Avarath." },
    "key_006": { name: "Buku Harian Tua", type: "key", val: 0, desc: "Berisi rahasia keluarga bangsawan." },
    "key_007": { name: "Fragmen Permata Jiwa", type: "key", val: 0, desc: "Satu dari tiga bagian segel." },
    "key_008": { name: "Suling Pemanggil Naga", type: "key", val: 0, desc: "Mengeluarkan nada yang hanya didengar naga." },
    "key_009": { name: "Cincin Stempel Valeryn", type: "key", val: 0, desc: "Memberi akses ke ruang strategi." },
    "key_010": { name: "Peta Harta Karun", type: "key", val: 500, desc: "Ditandai dengan simbol X merah." },
    "key_011": { name: "Batu Matahari", type: "key", val: 0, desc: "Menerangi ruangan gelap abadi." },
    "key_012": { name: "Kontrak Jiwa", type: "key", val: 0, desc: "Perjanjian tertulis dengan iblis." },
    "key_013": { name: "Kunci Menara Aerthale", type: "key", val: 0, desc: "Terbuat dari kristal murni." },
    "key_014": { name: "Lencana Kapten", type: "key", val: 0, desc: "Otoritas memimpin pasukan." },
    "key_015": { name: "Botol Kosong Ajaib", type: "key", val: 0, desc: "Bisa menampung napas naga." },
    "key_016": { name: "Resep Masakan Legendaris", type: "key", val: 0, desc: "Cara membuat hidangan dewa." },
    "key_017": { name: "Tengkorak Raja Terkutuk", type: "key", val: 0, desc: "Pintu masuk ke makam bawah tanah." }
});